name: Java 21 CI with Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:


      - uses: actions/checkout@v4
        name: Checkout Code

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
#          cache: 'maven'
#          cache-dependency-path: 'sub-project/pom.xml' # optional

      - name: Build with Maven
        run: mvn clean install

      - name: Generate JaCoCo Report
        run: mvn jacoco:report

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: calico-apps/KumaBudget-API
          file: ./target/site/jacoco/jacoco.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true